### PR TITLE
Update package.json - support react-redux 7

### PR DESCRIPTION
**Pull request by Saibamen**
Fixes https://github.com/gor181/react-notification-system-redux/issues/74

### CODE REVIEW

**Comment by aconital** [comment]
When is this getting released?

**Comment by Kyle-Ski** [comment]
Plus one on "When is this getting released?"

**Comment by piranna** [comment]
Can this be merged and released?

**Comment by epotockiy** [comment]
@gor181 this is small change, could you review this and merge?

**Comment by gor181** [comment]
Apologies for not responding sooner. Appreciate the PR. Merged and will release soonish

**Comment by gor181** [comment]
Released 2.0.1

**Pull request merged**
