### PR TITLE
Allow React v16 in the peerDependencies

### PR DESCRIPTION
**Pull request by roderik**

### CODE REVIEW

**Comment by gor181** [comment]
Hi @roderik.

Appreciate the PR 👍. Seems that the unit tests are failing:

```
> react-notification-system-redux@1.1.6 test /home/travis/build/gor181/react-notification-system-redux
> mocha test/__tests__/**/*
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
/home/travis/build/gor181/react-notification-system-redux/node_modules/enzyme/build/react-compat.js:144
      throw new Error('react-addons-test-utils is an implicit dependency in order to support react@0.13-14. ' + 'Please add the appropriate version to your devDependencies. ' + 'See https://github.com/airbnb/enzyme#installation');
      ^
Error: react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
```

Would you have time to look into it?
Most likely it's just compatibility of react 16 with enzyme.

**Comment by roderik** [comment]
Swamped ATM, but it should be fixed by using enzyme-adapter-react-16

**Comment by karl-run** [comment]
Since you're swamped @roderik I opened a PR with the upgraded enzyme as well.

**Comment by gor181** [comment]
Closing in favour of #56. Thanks @roderik for the efforts and directions :+1:

**Comment by roderik** [comment]
Nice @karl-run !

**Pull request closed without merging**
